server:
  port: 8080
  servlet:
    contextPath: /

spring:
  datasource:
    tomcat:
      max-wait: 5000
      max-active: 10
      test-on-borrow: true
    username: root
    password: toor
    url: jdbc:h2:file:./db/jwt_app_db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/migration/changelog-master.xml
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 12MB

jwt:
  token:
    secret: jwtappdemo
    expired: 3600000


